1.What is numpy?

<br>
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
<br>

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

2.Numpy Arrays Vs Python Sequences

<br>
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
<br>

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
<br>

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
<br>

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [1]:
# np.array

import numpy as np

a = np.array([1,2,3])
print(a)


[1 2 3]


In [2]:
# 2D and 3D

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [4]:
# dtype

np.array([1,2,3],dtype = float)  # changes datatype of any array

array([1., 2., 3.])

In [5]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
# with reshape

np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [7]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
# np.ones and np.zeros
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# np.random
np.random.random((3,4)) # from 0 to 1

array([[0.30729577, 0.31295034, 0.49609528, 0.08144596],
       [0.53510496, 0.26121698, 0.74728512, 0.09647247],
       [0.54893714, 0.42038885, 0.1181957 , 0.21840577]])

In [11]:
# np.linspace (linearly Space)  (lower range, upper range, no. of number we want to generate)
np.linspace(-10,10,10,dtype = int)   

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [12]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#  Array Attributes

In [13]:
a1 = np.arange(10,dtype = np.int32)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a2 = np.arange(12,dtype = float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [15]:
a3 = np.arange(8).reshape(2,2,2)  # (Number of rows, number of column, 3D matrix)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
# ndim
a3.ndim

3

In [17]:
# shape  (No. of 2D arrays, Shape of 2D arrays)
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
# size
print(a2.size)  # gives no. of elements

12


In [19]:
# itemsize - gives size of item in memory
a3.itemsize

4

In [20]:
a2.itemsize

8

In [21]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatype

In [22]:
# astype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

int32 (or int):
<br>

Also known as a 32-bit integer.
<br>
It uses 32 bits (4 bytes) of memory to store integer values.
<br>
Can represent values in the range of approximately -2.1 billion to 2.1 billion.
<br>
More memory-efficient than int64 but has a smaller range.

<br>
int64:
<br>

Also known as a 64-bit integer.
<br>
It uses 64 bits (8 bytes) of memory to store integer values.
<br>
Can represent a much wider range of values compared to int32.
<br>
It can represent values from approximately -9.2 quintillion to 9.2 

# Array Operations

In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
# scaler operations

# arithmetic

a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [26]:
# relational

a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
# vector operations
# arithmetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [28]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [29]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [30]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [31]:
a2/a1

C:\Users\surya\AppData\Local\Temp\ipykernel_7448\1139070438.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a2/a1


array([[        inf, 13.        ,  7.        ,  5.        ],
       [ 4.        ,  3.4       ,  3.        ,  2.71428571],
       [ 2.5       ,  2.33333333,  2.2       ,  2.09090909]])

In [32]:
a1 ** a2 # a1 to the power of a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

# Array Functions

In [33]:
a1 = np.random.random((3,3))
a1

array([[0.84299505, 0.73449107, 0.60114468],
       [0.10157075, 0.99839681, 0.6742514 ],
       [0.72579879, 0.87078156, 0.81764331]])

In [34]:
np.max(a1)
np.min(a1)
np.sum(a1)

6.367073415855132

In [35]:
# max/min/sum/prod
# 0 -> col and 1 -> row

np.prod(a1,axis = 0)

array([0.06214553, 0.63855591, 0.33140935])

In [36]:
np.max(a1,axis = 1)

array([0.84299505, 0.99839681, 0.87078156])

In [37]:
np.min(a1,axis = 0)

array([0.10157075, 0.73449107, 0.60114468])

In [38]:
# mean/median/std/var
np.var(a1,axis = 1)

array([0.00978289, 0.13748115, 0.00358657])

In [39]:
np.mean(a1,axis = 1)

array([0.72621027, 0.59140632, 0.80474122])

In [40]:
np.mean(a1,axis = 0)

array([0.55678819, 0.86788981, 0.6976798 ])

In [41]:
# trigonomoetric functions
np.sin(a1)

array([[0.74663886, 0.67020953, 0.56558685],
       [0.1013962 , 0.8406037 , 0.62431271],
       [0.66373312, 0.76483267, 0.72953602]])

In [42]:
np.cos(a1)

array([[0.6652296 , 0.74217194, 0.82468874],
       [0.99484612, 0.54165065, 0.78117453],
       [0.74796948, 0.64422898, 0.6839424 ]])

In [43]:
np.tan(a1)

array([[1.12237769, 0.90303809, 0.68581857],
       [0.10192149, 1.55192963, 0.79919747],
       [0.88737995, 1.18720625, 1.06666296]])

In [44]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [45]:
# log and exponents
np.exp(a1)

array([[2.323315  , 2.08442091, 1.82420574],
       [1.10690823, 2.71392739, 1.96256326],
       [2.06638104, 2.38877709, 2.26515527]])

In [46]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[36., 70., 42.],
       [61., 65., 37.]])

In [47]:
np.floor(np.random.random((2,3))*100)  # backwards

array([[86., 53., 63.],
       [90., 17., 96.]])

In [48]:
np.ceil(np.random.random((2,3))*100)  # forwards

array([[58., 32., 21.],
       [30., 14., 96.]])

# Indexing and Slicing

In [49]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [50]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a2[1,0]

4

In [53]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [54]:
a3[0,1,0]

2

In [55]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a1[2:5:2]

array([2, 4])

In [58]:
a2[0,:]  # column

array([0, 1, 2, 3])

In [59]:
a2[:,2]  # row

array([ 2,  6, 10])

In [60]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [61]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [62]:
a2[1,::3]

array([4, 7])

In [63]:
a2[0,:]

array([0, 1, 2, 3])

In [64]:
a2[:,2]

array([ 2,  6, 10])

In [65]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [66]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [67]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [68]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [69]:
a3[0,1,:]

array([3, 4, 5])

# Iterating

In [70]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
for i in a2:
    print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [73]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [75]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [76]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [77]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [79]:
np.hstack((a5,a4))

array([[12, 13, 14, 15,  0,  1,  2,  3],
       [16, 17, 18, 19,  4,  5,  6,  7],
       [20, 21, 22, 23,  8,  9, 10, 11]])

In [80]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [81]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [84]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [85]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]