In [5]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([28, 44, 25,  6, 24, 77, 75, 50, 62,  5, 96, 30, 92, 48,  3])

In [6]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[26, 37, 38, 65],
       [94, 91, 67, 31],
       [31, 36, 47, 66],
       [94, 67, 50, 18],
       [17, 62, 61, 25],
       [35, 60, 36, 68]])

In [7]:
np.sort(a)[::-1]

array([96, 92, 77, 75, 62, 50, 48, 44, 30, 28, 25, 24,  6,  5,  3])

In [8]:
np.sort(b,axis=0)  # 0 -> row , 1 -> column

array([[17, 36, 36, 18],
       [26, 37, 38, 25],
       [31, 60, 47, 31],
       [35, 62, 50, 65],
       [94, 67, 61, 66],
       [94, 91, 67, 68]])

In [9]:
# code
np.append(a,200)

array([ 28,  44,  25,   6,  24,  77,  75,  50,  62,   5,  96,  30,  92,
        48,   3, 200])

In [10]:
b

array([[26, 37, 38, 65],
       [94, 91, 67, 31],
       [31, 36, 47, 66],
       [94, 67, 50, 18],
       [17, 62, 61, 25],
       [35, 60, 36, 68]])

In [13]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[26.        , 37.        , 38.        , 65.        ,  0.50478207],
       [94.        , 91.        , 67.        , 31.        ,  0.85386214],
       [31.        , 36.        , 47.        , 66.        ,  0.25530868],
       [94.        , 67.        , 50.        , 18.        ,  0.564076  ],
       [17.        , 62.        , 61.        , 25.        ,  0.26782304],
       [35.        , 60.        , 36.        , 68.        ,  0.1007809 ]])

In [14]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [16]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [17]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [19]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [20]:
# code
a.shape

(15,)

In [21]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [24]:
np.expand_dims(a,axis=1)

array([[28],
       [44],
       [25],
       [ 6],
       [24],
       [77],
       [75],
       [50],
       [62],
       [ 5],
       [96],
       [30],
       [92],
       [48],
       [ 3]])

In [25]:
a

array([28, 44, 25,  6, 24, 77, 75, 50, 62,  5, 96, 30, 92, 48,  3])

In [26]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 5,  6,  8, 10, 12], dtype=int64),)

In [27]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([28, 44, 25,  6, 24,  0,  0, 50,  0,  5,  0, 30,  0, 48,  3])

In [28]:
np.where(a%2 == 0,0,a)

array([ 0,  0, 25,  0,  0, 77, 75,  0,  0,  5,  0,  0,  0,  0,  3])

In [29]:
a

array([28, 44, 25,  6, 24, 77, 75, 50, 62,  5, 96, 30, 92, 48,  3])

In [30]:
np.argmax(a)

10

In [31]:
np.argmin(a)

14

In [32]:
b

array([[26, 37, 38, 65],
       [94, 91, 67, 31],
       [31, 36, 47, 66],
       [94, 67, 50, 18],
       [17, 62, 61, 25],
       [35, 60, 36, 68]])

In [33]:
np.argmax(b,axis=0)

array([1, 1, 1, 5], dtype=int64)

In [34]:
np.argmax(b,axis=1)

array([3, 0, 3, 0, 1, 3], dtype=int64)

In [35]:
a

array([28, 44, 25,  6, 24, 77, 75, 50, 62,  5, 96, 30, 92, 48,  3])

In [36]:
np.cumsum(a)

array([ 28,  72,  97, 103, 127, 204, 279, 329, 391, 396, 492, 522, 614,
       662, 665], dtype=int32)

In [37]:
b

array([[26, 37, 38, 65],
       [94, 91, 67, 31],
       [31, 36, 47, 66],
       [94, 67, 50, 18],
       [17, 62, 61, 25],
       [35, 60, 36, 68]])

In [38]:
np.cumsum(b,axis=1)

array([[ 26,  63, 101, 166],
       [ 94, 185, 252, 283],
       [ 31,  67, 114, 180],
       [ 94, 161, 211, 229],
       [ 17,  79, 140, 165],
       [ 35,  95, 131, 199]], dtype=int32)

In [39]:
# np.cumprod
np.cumprod(a)

array([         28,        1232,       30800,      184800,     4435200,
         341510400,  -156523776,   763745792,   107598848,   537994240,
         107839488, -1059782656,  1284243456,  1514143744,   247463936],
      dtype=int32)

In [40]:
a

array([28, 44, 25,  6, 24, 77, 75, 50, 62,  5, 96, 30, 92, 48,  3])

In [41]:
np.percentile(a,50)

44.0

In [42]:
np.median(a)

44.0

In [43]:
a

array([28, 44, 25,  6, 24, 77, 75, 50, 62,  5, 96, 30, 92, 48,  3])

In [44]:
np.histogram(a,bins=[0,50,100])

(array([9, 6], dtype=int64), array([  0,  50, 100]))

In [45]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [46]:
a

array([28, 44, 25,  6, 24, 77, 75, 50, 62,  5, 96, 30, 92, 48,  3])

In [47]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50, 30])

In [48]:
a

array([28, 44, 25,  6, 24, 77, 75, 50, 62,  5, 96, 30, 92, 48,  3])

In [49]:
np.flip(a)

array([ 3, 48, 92, 30, 96,  5, 62, 50, 75, 77, 24,  6, 25, 44, 28])

In [50]:
b

array([[26, 37, 38, 65],
       [94, 91, 67, 31],
       [31, 36, 47, 66],
       [94, 67, 50, 18],
       [17, 62, 61, 25],
       [35, 60, 36, 68]])

In [51]:
np.flip(b,axis=1)

array([[65, 38, 37, 26],
       [31, 67, 91, 94],
       [66, 47, 36, 31],
       [18, 50, 67, 94],
       [25, 61, 62, 17],
       [68, 36, 60, 35]])

In [52]:
a

array([28, 44, 25,  6, 24, 77, 75, 50, 62,  5, 96, 30, 92, 48,  3])

In [53]:
np.put(a,[0,1],[110,530])

In [54]:
a

array([110, 530,  25,   6,  24,  77,  75,  50,  62,   5,  96,  30,  92,
        48,   3])

In [55]:
np.delete(a,[0,2,4])

array([530,   6,  77,  75,  50,  62,   5,  96,  30,  92,  48,   3])

In [56]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
np.intersect1d(m,n)

array([3, 4, 5])

In [58]:
np.setdiff1d(n,m)

array([6, 7])

In [59]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [60]:
m[np.in1d(m,1)]

array([1])

In [61]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 25, 25, 75, 75, 50, 62, 25, 75, 30, 75, 48, 25])